name: Research Methods
description: >
    A course for graduate students in the basic sciences. Covering data and information management best practices as they relate to research methods and reproducible science.
about: >
    Letisha R. Wyatt is the Biomedical Research & Data Specialist in the OHSU Library. Her research background is in neuropharmacology. As a Ph.D. (former NIH fellow, author of primary articles, and instructor of undergrads and graduate students) now in the library, Dr. Wyatt works to support the biomedical research community in areas of development of data literacy as they relate to best practices for research reproducibility. She helps facilitate efficiency and impactful research efforts as well as come up with solutions to tricky issues in the lab related to data management. Dr. Wyatt also plays a supportive role to faculty, students and staff by keep informed on current issues and resources in translational medicine as well as creating new data services and data science-related curricula for the Library and OHSU Graduate Studies. See more of her work via ORCID: 0000-0003-1026-5232.  

master_repo: false
url: "https://lrwyatt.github.io/MGRD-627"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Research Methods
  avatar:         "https://avatars1.githubusercontent.com/u/20113996?s=400&u=6fc607d217511c8c5656b0d6d054a9a3385b6805&v=4"
  email:          "wyattl@ohsu.edu"
  # Social networking links used in footer. Update and remove as you like.
  twitter: https://twitter.com/dr_lrwyatt
  github: https://github.com/lrwyatt
  linkedin: https://www.linkedin.com/in/letisha-r-wyatt
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
