name: Research Methods
description: >
    A course for graduate students in the basic sciences. Covering data and information management best practices as they relate to research methods and reproducible science.
about: >
    As a neuropharmacologist, my research interests involve investigating basic mechanisms of pharmacology and biochemistry as they relate to drug effects on the brain and the pathology of neurodegenerative diseases. I have studied ethanol intake behaviors in transgenic mice lacking purinergic P2X4 receptors and the role of adenosine homeostasis in mouse models of Parkinson's Disease and Stroke. I am a former NIH predoctoral fellow, have authored several primary research articles, and instructed students (high school through graduate) in the laboratory and classroom on their academic and professional development. See more of my work via ORCID: 0000-0003-1026-5232.

I am currently the Biomedical Research & Data Specialist in the Oregon Health & Science University (OHSU) Library and faculty within the Neuroscience Graduate Program. As a basic scientist with professional experience in clinical data management, I work to support the biomedical research community in areas of development of data literacy as they relate to best practices for research reproducibility. I help facilitate efficiency and impactful research efforts as well as come up with solutions to tricky issues in the lab related to data management. I also play a supportive role to faculty, students and staff by keep informed on current issues and resources in translational medicine as well as creating new data services and data science-related curricula for the Library and OHSU Graduate Studies.

As a woman of color, diversity in STEM is very important to me. I work hard to engage women in science, students of color, or those from low-income/first generation backgrounds throughout their undergraduate and graduate education. My goal in this is to develop useful resources and a sense of community around underrepresented minority student scholarship at OHSU as well as provide effective mentorship through their academic journey and scientific careers!

master_repo: false
url: "https://lrwyatt.github.io/MGRD-627"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Research Methods
  avatar:         "https://avatars1.githubusercontent.com/u/537678?s=240&v=4"
  email:          "wyattl@ohsu.edu"
  # Social networking links used in footer. Update and remove as you like.
  twitter: dr_lrwyatt
  github: https://github.com/lrwyatt
  linkedin: https://www.linkedin.com/in/letisha-r-wyatt
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
